

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class User : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the User entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public User()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public User(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.User> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.User.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void User_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LoginId
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.LoginId);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.LoginId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoginId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoginId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoginId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FullName
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.FullName);
            }
            set
            {
                global::LightSwitchApplication.User.DetailsClass.SetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.FullName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DisplayName
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.DisplayName);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DisplayName_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DisplayName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Achievement> Achievements
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Achievements);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Achievement> AchievementsQuery
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetQuery(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Achievements);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Achievement> AchievementNominations
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.AchievementNominations);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Achievement> AchievementNominationsQuery
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetQuery(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.AchievementNominations);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Rating> Ratings
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetValue(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Ratings);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Rating> RatingsQuery
        {
            get
            {
                return global::LightSwitchApplication.User.DetailsClass.GetQuery(this, global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Ratings);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.User,
                global::LightSwitchApplication.User.DetailsClass,
                global::LightSwitchApplication.User.DetailsClass.IImplementation,
                global::LightSwitchApplication.User.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>.Entry
                __UserEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>.Entry(
                    global::LightSwitchApplication.User.DetailsClass.__User_CreateNew,
                    global::LightSwitchApplication.User.DetailsClass.__User_Created,
                    global::LightSwitchApplication.User.DetailsClass.__User_AllowSaveWithErrors);
            private static global::LightSwitchApplication.User __User_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.User> es)
            {
                return new global::LightSwitchApplication.User(es);
            }
            private static void __User_Created(global::LightSwitchApplication.User e)
            {
                e.User_Created();
            }
            private static bool __User_AllowSaveWithErrors(global::LightSwitchApplication.User e)
            {
                bool result = false;
                e.User_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.User.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> LoginId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.LoginId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> FullName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.FullName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string> DisplayName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.DisplayName) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement> Achievements
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Achievements) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement> AchievementNominations
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.AchievementNominations) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Rating> Ratings
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Ratings) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Rating>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string LoginId { get; set; }
                new string FullName { get; set; }
                new global::System.Collections.IEnumerable Achievements { get; }
                new global::System.Collections.IEnumerable AchievementNominations { get; }
                new global::System.Collections.IEnumerable Ratings { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    LoginId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "LoginId",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._LoginId_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._LoginId_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._LoginId_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._LoginId_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._LoginId_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._LoginId_OnValueChanged);
                private static void _LoginId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._LoginId, sf);
                }
                private static bool _LoginId_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.LoginId_IsReadOnly(ref result);
                    return result;
                }
                private static void _LoginId_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LoginId_Validate(r);
                }
                private static string _LoginId_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.LoginId;
                }
                private static void _LoginId_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LoginId = v;
                }
                private static void _LoginId_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.LoginId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    FullName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "FullName",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._FullName_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._FullName_ComputeIsReadOnly,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._FullName_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._FullName_GetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._FullName_SetImplementationValue,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._FullName_OnValueChanged);
                private static void _FullName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._FullName, sf);
                }
                private static bool _FullName_ComputeIsReadOnly(global::LightSwitchApplication.User e)
                {
                    bool result = false;
                    e.FullName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FullName_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FullName_Validate(r);
                }
                private static string _FullName_GetImplementationValue(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.FullName;
                }
                private static void _FullName_SetImplementationValue(global::LightSwitchApplication.User.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FullName = v;
                }
                private static void _FullName_OnValueChanged(global::LightSwitchApplication.User e)
                {
                    e.FullName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry
                    DisplayName = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Entry(
                        "DisplayName",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._DisplayName_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._DisplayName_Validate,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._DisplayName_ComputeValue);
                private static void _DisplayName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._DisplayName, sf);
                }
                private static void _DisplayName_Validate(global::LightSwitchApplication.User e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DisplayName_Validate(r);
                }
                private static string _DisplayName_ComputeValue(global::LightSwitchApplication.User e)
                {
                    string value = default(string);
                    e.DisplayName_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>.Entry
                    Achievements = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>.Entry(
                        "Achievements",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Achievements_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Achievements_GetReferencedEntities,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Achievements_GetEntityCollection);
                private static void _Achievements_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Achievements, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Achievement> _Achievements_GetReferencedEntities(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Achievement, global::LightSwitchApplication.Achievement.DetailsClass>(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Achievements, ref d._Achievements);
                }
                private static global::System.Collections.IEnumerable _Achievements_GetEntityCollection(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Achievements;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>.Entry
                    AchievementNominations = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>.Entry(
                        "AchievementNominations",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._AchievementNominations_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._AchievementNominations_GetReferencedEntities,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._AchievementNominations_GetEntityCollection);
                private static void _AchievementNominations_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._AchievementNominations, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Achievement> _AchievementNominations_GetReferencedEntities(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Achievement, global::LightSwitchApplication.Achievement.DetailsClass>(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.AchievementNominations, ref d._AchievementNominations);
                }
                private static global::System.Collections.IEnumerable _AchievementNominations_GetEntityCollection(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.AchievementNominations;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Rating>.Entry
                    Ratings = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Rating>.Entry(
                        "Ratings",
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Ratings_Stub,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Ratings_GetReferencedEntities,
                        global::LightSwitchApplication.User.DetailsClass.PropertySetProperties._Ratings_GetEntityCollection);
                private static void _Ratings_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.User.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Rating>.Data> c, global::LightSwitchApplication.User.DetailsClass d, object sf)
                {
                    c(d, ref d._Ratings, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Rating> _Ratings_GetReferencedEntities(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Rating, global::LightSwitchApplication.Rating.DetailsClass>(global::LightSwitchApplication.User.DetailsClass.PropertySetProperties.Ratings, ref d._Ratings);
                }
                private static global::System.Collections.IEnumerable _Ratings_GetEntityCollection(global::LightSwitchApplication.User.DetailsClass d)
                {
                    return d.ImplementationEntity.Ratings;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _LoginId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _FullName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, string>.Data _DisplayName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>.Data _Achievements;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Achievement>.Data _AchievementNominations;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass, global::LightSwitchApplication.Rating>.Data _Ratings;
            
        }
    
        #endregion
    }
    
    #endregion
}
