//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 5/23/2013 8:10:54 PM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationData in the schema.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("LightSwitchApplication", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("LightSwitchApplication.Implementation", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for AchievementCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AchievementCategory> AchievementCategories
        {
            get
            {
                if ((this._AchievementCategories == null))
                {
                    this._AchievementCategories = base.CreateQuery<AchievementCategory>("AchievementCategories");
                }
                return this._AchievementCategories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AchievementCategory> _AchievementCategories;
        /// <summary>
        /// There are no comments for Achievements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Achievement> Achievements
        {
            get
            {
                if ((this._Achievements == null))
                {
                    this._Achievements = base.CreateQuery<Achievement>("Achievements");
                }
                return this._Achievements;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Achievement> _Achievements;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _Users;
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Rating> Ratings
        {
            get
            {
                if ((this._Ratings == null))
                {
                    this._Ratings = base.CreateQuery<Rating>("Ratings");
                }
                return this._Ratings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Rating> _Ratings;
        /// <summary>
        /// There are no comments for AchievementCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAchievementCategories(AchievementCategory achievementCategory)
        {
            base.AddObject("AchievementCategories", achievementCategory);
        }
        /// <summary>
        /// There are no comments for Achievements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAchievements(Achievement achievement)
        {
            base.AddObject("Achievements", achievement);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRatings(Rating rating)
        {
            base.AddObject("Ratings", rating);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"AchievementCategory\"><Key><PropertyRef Name=\"I" +
                "d\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:Stor" +
                "eGeneratedPattern=\"Identity\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nul" +
                "lable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed" +
                "\" /><Property Name=\"Description\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"2" +
                "55\" /><NavigationProperty Name=\"Achievements\" Relationship=\"LightSwitchApplicati" +
                "on.Achievement_AchievementCategory\" ToRole=\"Achievement\" FromRole=\"AchievementCa" +
                "tegory\" /></EntityType><EntityType Name=\"Achievement\"><Key><PropertyRef Name=\"Id" +
                "\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:Store" +
                "GeneratedPattern=\"Identity\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Null" +
                "able=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\"" +
                " /><Property Name=\"Description\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"25" +
                "5\" /><Property Name=\"NominatedOn\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Proper" +
                "ty Name=\"Achievement_AchievementCategory\" Type=\"Edm.Int32\" Nullable=\"false\" /><P" +
                "roperty Name=\"Achievement_User\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Na" +
                "me=\"Achievement_User1\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty N" +
                "ame=\"AchievementCategory\" Relationship=\"LightSwitchApplication.Achievement_Achie" +
                "vementCategory\" ToRole=\"AchievementCategory\" FromRole=\"Achievement\" /><Navigatio" +
                "nProperty Name=\"AchievedByUser\" Relationship=\"LightSwitchApplication.Achievement" +
                "_User\" ToRole=\"User\" FromRole=\"Achievement\" /><NavigationProperty Name=\"Nominate" +
                "dByUser\" Relationship=\"LightSwitchApplication.Achievement_User1\" ToRole=\"User\" F" +
                "romRole=\"Achievement\" /><NavigationProperty Name=\"Ratings\" Relationship=\"LightSw" +
                "itchApplication.Rating_Achievement\" ToRole=\"Rating\" FromRole=\"Achievement\" /></E" +
                "ntityType><EntityType Name=\"User\"><Key><PropertyRef Name=\"Id\" /></Key><Property " +
                "Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Id" +
                "entity\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" Concurr" +
                "encyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" /><Property Name=\"L" +
                "oginId\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"Ful" +
                "lName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><NavigationProperty " +
                "Name=\"Achievements\" Relationship=\"LightSwitchApplication.Achievement_User\" ToRol" +
                "e=\"Achievement\" FromRole=\"User\" /><NavigationProperty Name=\"AchievementNominatio" +
                "ns\" Relationship=\"LightSwitchApplication.Achievement_User1\" ToRole=\"Achievement\"" +
                " FromRole=\"User\" /><NavigationProperty Name=\"Ratings\" Relationship=\"LightSwitchA" +
                "pplication.Rating_User\" ToRole=\"Rating\" FromRole=\"User\" /></EntityType><EntityTy" +
                "pe Name=\"Rating\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"E" +
                "dm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Proper" +
                "ty Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" " +
                "annotation:StoreGeneratedPattern=\"Computed\" /><Property Name=\"RatedOn\" Type=\"Edm" +
                ".DateTime\" Nullable=\"false\" /><Property Name=\"Comment\" Type=\"Edm.String\" Nullabl" +
                "e=\"false\" MaxLength=\"255\" /><Property Name=\"Rating_Achievement\" Type=\"Edm.Int32\"" +
                " Nullable=\"false\" /><Property Name=\"Rating_User\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><NavigationProperty Name=\"Achievement\" Relationship=\"LightSwitchApplication" +
                ".Rating_Achievement\" ToRole=\"Achievement\" FromRole=\"Rating\" /><NavigationPropert" +
                "y Name=\"RatedByUser\" Relationship=\"LightSwitchApplication.Rating_User\" ToRole=\"U" +
                "ser\" FromRole=\"Rating\" /></EntityType><Association Name=\"Achievement_Achievement" +
                "Category\"><End Role=\"AchievementCategory\" Type=\"LightSwitchApplication.Achieveme" +
                "ntCategory\" Multiplicity=\"1\" /><End Role=\"Achievement\" Type=\"LightSwitchApplicat" +
                "ion.Achievement\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Achi" +
                "evementCategory\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Achieveme" +
                "nt\"><PropertyRef Name=\"Achievement_AchievementCategory\" /></Dependent></Referent" +
                "ialConstraint></Association><Association Name=\"Achievement_User\"><End Role=\"User" +
                "\" Type=\"LightSwitchApplication.User\" Multiplicity=\"1\" /><End Role=\"Achievement\" " +
                "Type=\"LightSwitchApplication.Achievement\" Multiplicity=\"*\" /><ReferentialConstra" +
                "int><Principal Role=\"User\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=" +
                "\"Achievement\"><PropertyRef Name=\"Achievement_User\" /></Dependent></ReferentialCo" +
                "nstraint></Association><Association Name=\"Achievement_User1\"><End Role=\"User\" Ty" +
                "pe=\"LightSwitchApplication.User\" Multiplicity=\"1\" /><End Role=\"Achievement\" Type" +
                "=\"LightSwitchApplication.Achievement\" Multiplicity=\"*\" /><ReferentialConstraint>" +
                "<Principal Role=\"User\"><PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Ach" +
                "ievement\"><PropertyRef Name=\"Achievement_User1\" /></Dependent></ReferentialConst" +
                "raint></Association><Association Name=\"Rating_Achievement\"><End Role=\"Achievemen" +
                "t\" Type=\"LightSwitchApplication.Achievement\" Multiplicity=\"1\"><OnDelete Action=\"" +
                "Cascade\" /></End><End Role=\"Rating\" Type=\"LightSwitchApplication.Rating\" Multipl" +
                "icity=\"*\" /><ReferentialConstraint><Principal Role=\"Achievement\"><PropertyRef Na" +
                "me=\"Id\" /></Principal><Dependent Role=\"Rating\"><PropertyRef Name=\"Rating_Achieve" +
                "ment\" /></Dependent></ReferentialConstraint></Association><Association Name=\"Rat" +
                "ing_User\"><End Role=\"User\" Type=\"LightSwitchApplication.User\" Multiplicity=\"1\" /" +
                "><End Role=\"Rating\" Type=\"LightSwitchApplication.Rating\" Multiplicity=\"*\" /><Ref" +
                "erentialConstraint><Principal Role=\"User\"><PropertyRef Name=\"Id\" /></Principal><" +
                "Dependent Role=\"Rating\"><PropertyRef Name=\"Rating_User\" /></Dependent></Referent" +
                "ialConstraint></Association><EntityContainer Name=\"ApplicationData\" m:IsDefaultE" +
                "ntityContainer=\"true\"><EntitySet Name=\"AchievementCategories\" EntityType=\"LightS" +
                "witchApplication.AchievementCategory\" /><EntitySet Name=\"Achievements\" EntityTyp" +
                "e=\"LightSwitchApplication.Achievement\" /><EntitySet Name=\"Users\" EntityType=\"Lig" +
                "htSwitchApplication.User\" /><EntitySet Name=\"Ratings\" EntityType=\"LightSwitchApp" +
                "lication.Rating\" /><AssociationSet Name=\"Achievement_AchievementCategory\" Associ" +
                "ation=\"LightSwitchApplication.Achievement_AchievementCategory\"><End Role=\"Achiev" +
                "ementCategory\" EntitySet=\"AchievementCategories\" /><End Role=\"Achievement\" Entit" +
                "ySet=\"Achievements\" /></AssociationSet><AssociationSet Name=\"Achievement_User\" A" +
                "ssociation=\"LightSwitchApplication.Achievement_User\"><End Role=\"User\" EntitySet=" +
                "\"Users\" /><End Role=\"Achievement\" EntitySet=\"Achievements\" /></AssociationSet><A" +
                "ssociationSet Name=\"Achievement_User1\" Association=\"LightSwitchApplication.Achie" +
                "vement_User1\"><End Role=\"User\" EntitySet=\"Users\" /><End Role=\"Achievement\" Entit" +
                "ySet=\"Achievements\" /></AssociationSet><AssociationSet Name=\"Rating_Achievement\"" +
                " Association=\"LightSwitchApplication.Rating_Achievement\"><End Role=\"Achievement\"" +
                " EntitySet=\"Achievements\" /><End Role=\"Rating\" EntitySet=\"Ratings\" /></Associati" +
                "onSet><AssociationSet Name=\"Rating_User\" Association=\"LightSwitchApplication.Rat" +
                "ing_User\"><End Role=\"User\" EntitySet=\"Users\" /><End Role=\"Rating\" EntitySet=\"Rat" +
                "ings\" /></AssociationSet><FunctionImport Name=\"GetMissingUs";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @"ers"" ReturnType=""Collection(LightSwitchApplication.User)"" EntitySet=""Users"" m:HttpMethod=""GET"" /><FunctionImport Name=""Microsoft_LightSwitch_GetCanInformation"" ReturnType=""Edm.String"" m:HttpMethod=""GET""><Parameter Name=""dataServiceMembers"" Type=""Edm.String"" Mode=""In"" /></FunctionImport></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.AchievementCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AchievementCategories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class AchievementCategory : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AchievementCategory object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="description">Initial value of Description.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AchievementCategory CreateAchievementCategory(int ID, byte[] rowVersion, string description)
        {
            AchievementCategory achievementCategory = new AchievementCategory();
            achievementCategory.Id = ID;
            achievementCategory.RowVersion = rowVersion;
            achievementCategory.Description = description;
            return achievementCategory;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                if (object.Equals(this.Description, value))
                {
                    return;
                }
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Achievements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Achievement> Achievements
        {
            get
            {
                this.@__Achievements.EnsureValueInitialized();
                return this._Achievements;
            }
            set
            {
                this._Achievements = value;
                this.OnPropertyChanged("Achievements");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Achievement> _Achievements = new global::System.Data.Services.Client.DataServiceCollection<Achievement>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Achievement in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Achievements")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Achievement : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Achievement object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="nominatedOn">Initial value of NominatedOn.</param>
        /// <param name="achievement_AchievementCategory">Initial value of Achievement_AchievementCategory.</param>
        /// <param name="achievement_User">Initial value of Achievement_User.</param>
        /// <param name="achievement_User1">Initial value of Achievement_User1.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Achievement CreateAchievement(int ID, byte[] rowVersion, string description, global::System.DateTime nominatedOn, int achievement_AchievementCategory, int achievement_User, int achievement_User1)
        {
            Achievement achievement = new Achievement();
            achievement.Id = ID;
            achievement.RowVersion = rowVersion;
            achievement.Description = description;
            achievement.NominatedOn = nominatedOn;
            achievement.Achievement_AchievementCategory = achievement_AchievementCategory;
            achievement.Achievement_User = achievement_User;
            achievement.Achievement_User1 = achievement_User1;
            return achievement;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                if (object.Equals(this.Description, value))
                {
                    return;
                }
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property NominatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime NominatedOn
        {
            get
            {
                return this._NominatedOn;
            }
            set
            {
                this.OnNominatedOnChanging(value);
                if (object.Equals(this.NominatedOn, value))
                {
                    return;
                }
                this._NominatedOn = value;
                this.OnNominatedOnChanged();
                this.OnPropertyChanged("NominatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _NominatedOn;
        partial void OnNominatedOnChanging(global::System.DateTime value);
        partial void OnNominatedOnChanged();
        /// <summary>
        /// There are no comments for Property Achievement_AchievementCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Achievement_AchievementCategory
        {
            get
            {
                return this._Achievement_AchievementCategory;
            }
            set
            {
                this.OnAchievement_AchievementCategoryChanging(value);
                if (object.Equals(this.Achievement_AchievementCategory, value))
                {
                    return;
                }
                this._Achievement_AchievementCategory = value;
                this.OnAchievement_AchievementCategoryChanged();
                this.OnPropertyChanged("Achievement_AchievementCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Achievement_AchievementCategory;
        partial void OnAchievement_AchievementCategoryChanging(int value);
        partial void OnAchievement_AchievementCategoryChanged();
        /// <summary>
        /// There are no comments for Property Achievement_User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Achievement_User
        {
            get
            {
                return this._Achievement_User;
            }
            set
            {
                this.OnAchievement_UserChanging(value);
                if (object.Equals(this.Achievement_User, value))
                {
                    return;
                }
                this._Achievement_User = value;
                this.OnAchievement_UserChanged();
                this.OnPropertyChanged("Achievement_User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Achievement_User;
        partial void OnAchievement_UserChanging(int value);
        partial void OnAchievement_UserChanged();
        /// <summary>
        /// There are no comments for Property Achievement_User1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Achievement_User1
        {
            get
            {
                return this._Achievement_User1;
            }
            set
            {
                this.OnAchievement_User1Changing(value);
                if (object.Equals(this.Achievement_User1, value))
                {
                    return;
                }
                this._Achievement_User1 = value;
                this.OnAchievement_User1Changed();
                this.OnPropertyChanged("Achievement_User1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Achievement_User1;
        partial void OnAchievement_User1Changing(int value);
        partial void OnAchievement_User1Changed();
        /// <summary>
        /// There are no comments for AchievementCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AchievementCategory AchievementCategory
        {
            get
            {
                this.@__AchievementCategory.EnsureValueInitialized();
                return this._AchievementCategory;
            }
            set
            {
                AchievementCategory previous = this.AchievementCategory;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._AchievementCategory = null;
                    this.@__AchievementCategory.OnValueSet();
                    previous.Achievements.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Achievement_AchievementCategory = value.Id;
                    }
                    else
                    {
                        this.Achievement_AchievementCategory = default(int);
                    }
                }
                this._AchievementCategory = value;
                this.@__AchievementCategory.OnValueSet();
                if ((value != null))
                {
                    value.@__Achievements.Add(this);
                }
                this.___OnPropertyChanged("AchievementCategory");
                this.OnPropertyChanged("AchievementCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private AchievementCategory _AchievementCategory;
        /// <summary>
        /// There are no comments for AchievedByUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User AchievedByUser
        {
            get
            {
                this.@__AchievedByUser.EnsureValueInitialized();
                return this._AchievedByUser;
            }
            set
            {
                User previous = this.AchievedByUser;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._AchievedByUser = null;
                    this.@__AchievedByUser.OnValueSet();
                    previous.Achievements.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Achievement_User = value.Id;
                    }
                    else
                    {
                        this.Achievement_User = default(int);
                    }
                }
                this._AchievedByUser = value;
                this.@__AchievedByUser.OnValueSet();
                if ((value != null))
                {
                    value.@__Achievements.Add(this);
                }
                this.___OnPropertyChanged("AchievedByUser");
                this.OnPropertyChanged("AchievedByUser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _AchievedByUser;
        /// <summary>
        /// There are no comments for NominatedByUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User NominatedByUser
        {
            get
            {
                this.@__NominatedByUser.EnsureValueInitialized();
                return this._NominatedByUser;
            }
            set
            {
                User previous = this.NominatedByUser;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._NominatedByUser = null;
                    this.@__NominatedByUser.OnValueSet();
                    previous.AchievementNominations.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Achievement_User1 = value.Id;
                    }
                    else
                    {
                        this.Achievement_User1 = default(int);
                    }
                }
                this._NominatedByUser = value;
                this.@__NominatedByUser.OnValueSet();
                if ((value != null))
                {
                    value.@__AchievementNominations.Add(this);
                }
                this.___OnPropertyChanged("NominatedByUser");
                this.OnPropertyChanged("NominatedByUser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _NominatedByUser;
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Rating> Ratings
        {
            get
            {
                this.@__Ratings.EnsureValueInitialized();
                return this._Ratings;
            }
            set
            {
                this._Ratings = value;
                this.OnPropertyChanged("Ratings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Rating> _Ratings = new global::System.Data.Services.Client.DataServiceCollection<Rating>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class User : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="loginId">Initial value of LoginId.</param>
        /// <param name="fullName">Initial value of FullName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(int ID, byte[] rowVersion, string loginId, string fullName)
        {
            User user = new User();
            user.Id = ID;
            user.RowVersion = rowVersion;
            user.LoginId = loginId;
            user.FullName = fullName;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property LoginId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LoginId
        {
            get
            {
                return this._LoginId;
            }
            set
            {
                this.OnLoginIdChanging(value);
                if (object.Equals(this.LoginId, value))
                {
                    return;
                }
                this._LoginId = value;
                this.OnLoginIdChanged();
                this.OnPropertyChanged("LoginId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LoginId;
        partial void OnLoginIdChanging(string value);
        partial void OnLoginIdChanged();
        /// <summary>
        /// There are no comments for Property FullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FullName
        {
            get
            {
                return this._FullName;
            }
            set
            {
                this.OnFullNameChanging(value);
                if (object.Equals(this.FullName, value))
                {
                    return;
                }
                this._FullName = value;
                this.OnFullNameChanged();
                this.OnPropertyChanged("FullName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FullName;
        partial void OnFullNameChanging(string value);
        partial void OnFullNameChanged();
        /// <summary>
        /// There are no comments for Achievements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Achievement> Achievements
        {
            get
            {
                this.@__Achievements.EnsureValueInitialized();
                return this._Achievements;
            }
            set
            {
                this._Achievements = value;
                this.OnPropertyChanged("Achievements");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Achievement> _Achievements = new global::System.Data.Services.Client.DataServiceCollection<Achievement>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for AchievementNominations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Achievement> AchievementNominations
        {
            get
            {
                this.@__AchievementNominations.EnsureValueInitialized();
                return this._AchievementNominations;
            }
            set
            {
                this._AchievementNominations = value;
                this.OnPropertyChanged("AchievementNominations");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Achievement> _AchievementNominations = new global::System.Data.Services.Client.DataServiceCollection<Achievement>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Ratings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Rating> Ratings
        {
            get
            {
                this.@__Ratings.EnsureValueInitialized();
                return this._Ratings;
            }
            set
            {
                this._Ratings = value;
                this.OnPropertyChanged("Ratings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Rating> _Ratings = new global::System.Data.Services.Client.DataServiceCollection<Rating>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Rating in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Ratings")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Rating : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Rating object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="ratedOn">Initial value of RatedOn.</param>
        /// <param name="comment">Initial value of Comment.</param>
        /// <param name="rating_Achievement">Initial value of Rating_Achievement.</param>
        /// <param name="rating_User">Initial value of Rating_User.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Rating CreateRating(int ID, byte[] rowVersion, global::System.DateTime ratedOn, string comment, int rating_Achievement, int rating_User)
        {
            Rating rating = new Rating();
            rating.Id = ID;
            rating.RowVersion = rowVersion;
            rating.RatedOn = ratedOn;
            rating.Comment = comment;
            rating.Rating_Achievement = rating_Achievement;
            rating.Rating_User = rating_User;
            return rating;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property RatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime RatedOn
        {
            get
            {
                return this._RatedOn;
            }
            set
            {
                this.OnRatedOnChanging(value);
                if (object.Equals(this.RatedOn, value))
                {
                    return;
                }
                this._RatedOn = value;
                this.OnRatedOnChanged();
                this.OnPropertyChanged("RatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _RatedOn;
        partial void OnRatedOnChanging(global::System.DateTime value);
        partial void OnRatedOnChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                if (object.Equals(this.Comment, value))
                {
                    return;
                }
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property Rating_Achievement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Rating_Achievement
        {
            get
            {
                return this._Rating_Achievement;
            }
            set
            {
                this.OnRating_AchievementChanging(value);
                if (object.Equals(this.Rating_Achievement, value))
                {
                    return;
                }
                this._Rating_Achievement = value;
                this.OnRating_AchievementChanged();
                this.OnPropertyChanged("Rating_Achievement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Rating_Achievement;
        partial void OnRating_AchievementChanging(int value);
        partial void OnRating_AchievementChanged();
        /// <summary>
        /// There are no comments for Property Rating_User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Rating_User
        {
            get
            {
                return this._Rating_User;
            }
            set
            {
                this.OnRating_UserChanging(value);
                if (object.Equals(this.Rating_User, value))
                {
                    return;
                }
                this._Rating_User = value;
                this.OnRating_UserChanged();
                this.OnPropertyChanged("Rating_User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Rating_User;
        partial void OnRating_UserChanging(int value);
        partial void OnRating_UserChanged();
        /// <summary>
        /// There are no comments for Achievement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Achievement Achievement
        {
            get
            {
                this.@__Achievement.EnsureValueInitialized();
                return this._Achievement;
            }
            set
            {
                Achievement previous = this.Achievement;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Achievement = null;
                    this.@__Achievement.OnValueSet();
                    previous.Ratings.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Rating_Achievement = value.Id;
                    }
                    else
                    {
                        this.Rating_Achievement = default(int);
                    }
                }
                this._Achievement = value;
                this.@__Achievement.OnValueSet();
                if ((value != null))
                {
                    value.@__Ratings.Add(this);
                }
                this.___OnPropertyChanged("Achievement");
                this.OnPropertyChanged("Achievement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Achievement _Achievement;
        /// <summary>
        /// There are no comments for RatedByUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User RatedByUser
        {
            get
            {
                this.@__RatedByUser.EnsureValueInitialized();
                return this._RatedByUser;
            }
            set
            {
                User previous = this.RatedByUser;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._RatedByUser = null;
                    this.@__RatedByUser.OnValueSet();
                    previous.Ratings.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Rating_User = value.Id;
                    }
                    else
                    {
                        this.Rating_User = default(int);
                    }
                }
                this._RatedByUser = value;
                this.@__RatedByUser.OnValueSet();
                if ((value != null))
                {
                    value.@__Ratings.Add(this);
                }
                this.___OnPropertyChanged("RatedByUser");
                this.OnPropertyChanged("RatedByUser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _RatedByUser;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
