// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"UserCode/Achievement.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"UserCode/BrowseAchievements.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"UserCode/EditAchievement.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"UserCode/EditRating.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"UserCode/Rating.js\"></script>");
